// Generate a complete, searchable page from content.js. No dependencies required.
import { readFileSync, writeFileSync } from 'node:fs';
import { runInNewContext } from 'node:vm';

const root = new URL('./', import.meta.url);
const context = { window: {} };
runInNewContext(readFileSync(new URL('content.js', root), 'utf8'), context);
const p = context.window.ACADEMIC_PROFILE;
if (!p?.name || !p?.website) throw new Error('The profile needs a name and website.');
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
const href = value => {
  const url = new URL(value, p.website);
  if (!['https:', 'http:', 'mailto:'].includes(url.protocol)) throw new Error(`Unsupported URL: ${value}`);
  return esc(value);
};
const link = (text, url, css = '') => `<a${css ? ` class="${esc(css)}"` : ''} href="${href(url)}">${esc(text)}</a>`;
const authors = value => esc(value).split(esc(p.name)).join(`<strong>${esc(p.name)}</strong>`);
const aboutText = text => {
  const people = new Map(p.people.map(person => [person.name, person.url]));
  const names = [...people.keys()].map(name => name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'));
  return text.split(new RegExp(`(${names.join('|')})`, 'g')).map(part => people.has(part) ? link(part, people.get(part)) : esc(part)).join('');
};
const linkLabels = { paper: 'Paper', code: 'Code', conference: 'Conference', review: 'OpenReview', simulations: 'Abaqus tools', project: 'Project', data: 'Data' };
const publication = (item, level = 3) => `<article class="publication">
  <span class="publication-year">${esc(item.year)}</span>
  <div class="publication-body">
    <h${level}>${esc(item.title)}</h${level}>
    <p class="publication-authors">${authors(item.authors)}</p>
    <p class="publication-venue">${esc(item.venue)}${item.status ? ` <span class="publication-status">${esc(item.status)}</span>` : ''}</p>
    <div class="publication-links">${Object.entries(item.links || {}).map(([key, url]) => link(linkLabels[key] || key, url)).join(' ')}</div>
  </div>
</article>`;
const sections = [['about', 'About'], ['research', 'Research'], ['publications', 'Publications'], ['software', 'Software'], ['background', 'Background'], ['contact', 'Contact']];
const structuredData = {
  '@context': 'https://schema.org', '@type': 'Person', name: p.name, alternateName: p.nativeName,
  url: p.website, image: new URL(p.photo, p.website).href, jobTitle: p.position,
  affiliation: { '@type': 'CollegeOrUniversity', name: p.institution },
  sameAs: Object.values(p.links), email: `mailto:${p.email}`
};

const html = `<!doctype html>
<!-- Generated by node build.mjs. Edit content.js for profile changes. -->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="${esc(p.description)}">
  ${p.draft ? '<meta name="robots" content="noindex, nofollow">' : '<meta name="robots" content="index, follow">'}
  <meta name="color-scheme" content="light">
  <title>${esc(p.name)} | Academic Homepage</title>
  <link rel="canonical" href="${href(p.website)}">
  <meta property="og:type" content="profile">
  <meta property="og:title" content="${esc(p.name)} | Academic Homepage">
  <meta property="og:description" content="${esc(p.description)}">
  <meta property="og:url" content="${href(p.website)}">
  <meta property="og:image" content="${href(new URL(p.photo, p.website).href)}">
  <meta name="twitter:card" content="summary">
  <link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 40 40'%3E%3Crect width='40' height='40' rx='10' fill='%23043361'/%3E%3Ctext x='20' y='27' text-anchor='middle' font-family='sans-serif' font-size='23' fill='white'%3EC%3C/text%3E%3C/svg%3E">
  <link rel="preload" href="./assets/fonts/nunito-regular.ttf" as="font" type="font/ttf" crossorigin>
  <link rel="stylesheet" href="./styles.css">
  <script type="application/ld+json">${JSON.stringify(structuredData).replace(/</g, '\\u003c')}</script>
  <script src="./app.js" defer></script>
</head>
<body>
  <a class="skip-link" href="#main">Skip to content</a>
  ${p.draft ? '<div class="draft-notice">This homepage is a draft.</div>' : ''}
  <div class="page-layout">
    <aside class="profile" aria-label="Researcher profile">
      <div class="portrait"><img src="${href(p.photo)}" alt="Portrait of ${esc(p.name)}" width="300" height="300" fetchpriority="high"></div>
      <div class="profile-details">
        <h1>${esc(p.name)}</h1>
        <p class="native-name" lang="zh-Hans">${esc(p.nativeName)}</p>
        <p class="position">${esc(p.position)}</p>
        <p class="institution">${link(p.institution, p.links.faculty)}</p>
        <p class="location">${esc(p.location)}</p>
        <div class="profile-links">${link('Email', `mailto:${p.email}`)} ${link('Google Scholar', p.links.scholar)} ${link('ORCID', p.links.orcid)} ${link('GitHub', p.links.github)}</div>
        ${link('Download CV ↗', p.cv, 'cv-link')}
      </div>
      <nav class="profile-nav" aria-label="Main navigation">
        ${sections.map(([id, label], i) => `<a class="nav-link${i === 0 ? ' active' : ''}" href="#${id}"${i === 0 ? ' aria-current="location"' : ''}>${label}</a>`).join('\n        ')}
      </nav>
    </aside>
    <main id="main">
      <section class="about section" id="about" aria-labelledby="about-heading">
        <h2 id="about-heading">About Me</h2>
        <div class="about-copy">${p.about.map(text => `<p>${aboutText(text)}</p>`).join('\n        ')}</div>
      </section>
      <section class="section" id="research" aria-labelledby="research-heading">
        <h2 id="research-heading">Research Interests</h2>
        <ul class="research-list">${p.research.map(item => `<li class="research-item"><strong>${esc(item.title)}.</strong> ${esc(item.description)}</li>`).join('\n        ')}</ul>
      </section>
      <section class="section" id="publications" aria-labelledby="publications-heading">
        <div class="section-title-row"><h2 id="publications-heading">Publications</h2>${link('Google Scholar ↗', p.links.scholar, 'text-link')}</div>
        <div class="publication-list">${p.publications.map(item => publication(item)).join('\n        ')}</div>
        ${(p.preprints || []).length ? `<div class="preprints"><h3 class="subheading">Preprints</h3>${p.preprints.map(item => publication(item, 4)).join('\n        ')}</div>` : ''}
      </section>
      <section class="section" id="software" aria-labelledby="software-heading">
        <h2 id="software-heading">Research Software</h2>
        <div class="software-list">${p.projects.map(item => `<article class="software-item"><h3>${link(item.title, item.url)} <span class="project-label">${esc(item.label)}</span></h3><p>${esc(item.description)}</p></article>`).join('\n        ')}</div>
        <p class="contributions">I also contribute to ${p.contributions.map(item => `${link(item.name, item.url)} (${esc(item.description)})`).join(' and ')}.</p>
      </section>
      <section class="section" id="background" aria-labelledby="background-heading">
        <h2 id="background-heading">Education &amp; Experience</h2>
        <div class="timeline">${p.experience.map(item => `<div class="timeline-item"><span class="timeline-years">${esc(item.years)}</span><div><h3>${esc(item.institution)}</h3><p>${esc(item.role)}</p>${item.detail ? `<p class="timeline-detail">${esc(item.detail)}</p>` : ''}</div></div>`).join('\n        ')}</div>
        <h3 class="subheading awards-heading">Selected Honors</h3>
        <ul class="awards-list">${p.awards.map(item => `<li>${esc(item.title)}${item.institution ? `, ${esc(item.institution)}` : ''}${item.year ? ` <span class="award-year">(${esc(item.year)})</span>` : ''}.</li>`).join('\n        ')}</ul>
      </section>
      <section class="section contact-section" id="contact" aria-labelledby="contact-heading">
        <h2 id="contact-heading">Contact</h2>
        <p>${esc(p.contactIntro)}</p>
        <dl class="contact-details">
          <div><dt>Email</dt><dd>${link(p.email, `mailto:${p.email}`)}</dd></div>
          <div><dt>Affiliation</dt><dd>${esc(p.department)}<br>${esc(p.institution)}<br>${esc(p.location)}</dd></div>
          <div><dt>University</dt><dd>${link('Official researcher profile ↗', p.links.faculty)}</dd></div>
        </dl>
      </section>
      <footer class="site-footer"><span>${esc(p.name)} · Updated ${esc(p.updated)}</span><a href="#about">Back to top ↑</a></footer>
    </main>
  </div>
</body>
</html>
`;
writeFileSync(new URL('index.html', root), html.replace(/^[\t ]+$/gm, ''));
writeFileSync(new URL('robots.txt', root), `User-agent: *\n${p.draft ? 'Disallow: /' : 'Allow: /'}\nSitemap: ${p.website}sitemap.xml\n`);
writeFileSync(new URL('sitemap.xml', root), `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>${esc(p.website)}</loc></url></urlset>\n`);
console.log(`Generated homepage for ${p.name}: ${p.publications.length} publications, ${(p.preprints || []).length} preprints.`);
